name: Build on Linux

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: napalys/attachable-clicker-docker:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cmake and build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
