name: CodeQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: napalys/attachable-clicker-docker:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: git config --global --add safe.directory /__w/Attachable-clicker/Attachable-clicker

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp
          config-file: .github/codeql/codeql-config.yml

      - name: Build the code
        run: |
          cmake -S . -B build
          cmake --build build --config Release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: '/default'
