name: CodeQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: napalys/attachable-clicker-docker:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp

      - name: Build the code
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          category: '/default'
