name: Build and Analyze with CodeQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    container:
      image: napalys/attachable-clicker-docker:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /__w/Attachable-clicker/Attachable-clicker

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp

      - name: Configure Git Safe Directory Again
        run: git config --global --add safe.directory /__w/Attachable-clicker/Attachable-clicker

      - name: Cmake and build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/default"

      - name: Configure Git Safe Directory Again
        run: git config --global --add safe.directory /__w/Attachable-clicker/Attachable-clicker
