name: Deploy windows

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v3

      - name: Cmake and build
        run: |
          cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake -B build
          cmake --build build --config Release
        shell: cmd

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: InjectionClicker-${{ github.run_number }}
          path: build/Release/

      - name: Zip the application
        run: |
          Compress-Archive -Path build/Release/* -DestinationPath InjectionClicker-${{ github.run_number }}.zip
        shell: powershell

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: ./InjectionClicker-${{ github.run_number }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}